version: "3.9"

services:
  openui:
    image: hvckfy/openchat-openui:latest
    container_name: openchat-openui

    environment:
      NEXT_PUBLIC_API_URL: https://dev.openchat.overhead-lines.ru/api
      NODE_TLS_REJECT_UNAUTHORIZED: "0"

    restart: unless-stopped

    networks:
      - web

networks:
  web:
    external: true