version: '3.8'
services:
  message-service:
    image: hvckfy/openchat-messageservice:latest
    environment:
      DBHost: 9.9.9.17
      DBPort: 5433
      DBUser: messageuser
      DBPass: messagepass
      DBName: messagedb
      MTLSPort: 48080
      MTLSCaCrt: /home/certs/ca.crt
      MTLSServiceSrt: /home/certs/message-service.crt
      MTLSServiceKey: /home/certs/message-service.key
    restart: unless-stopped
    volumes:
      - /home/certs/ca.crt:/home/certs/ca.crt:ro
      - /home/certs/message-service.crt:/home/certs/message-service.crt:ro
      - /home/certs/message-service.key:/home/certs/message-service.key:ro
      - /home/heckfy/logs/message-service/:/root/logs/
    networks:
      - web
networks:
  web:
    external: true