import Foundation

// LiveCore wraps the real Go core, generated by gomobile bind (see
// app/golang/mobile's package doc comment) into the OpenChatMobile.
// xcframework. It only compiles when that framework is linked, gated by
// `canImport` below — until then (including inside this package's own
// `swift build`, which has no Xcode project or linked framework at all)
// the rest of OpenChatKit only ever sees MockCore, and still builds.
//
// ⚠️ PARTIALLY VERIFIED — corrected once already against real compiler
// errors from an actual `gomobile bind` build (see git history / chat log
// for the two rounds of fixes), so the points below are now confirmed:
//   - Bound Go struct types (`Wallet`, `Session`) come out as `MobileWallet`/
//     `MobileSession` — gobind prefixes every exported symbol from package
//     `mobile` with "Mobile", same as the free functions.
//   - Free Go functions (`MobileGenerateMnemonic`, `MobileCreateWallet`,
//     `MobileImportWallet`, `MobileParseContactCode`, `MobileNewSession`)
//     are plain C-style Swift functions — they keep the explicit
//     `NSErrorPointer`/`&error` out-parameter, no auto-bridging.
//   - Go methods on bound types (`Session.connect`, `.sendText`, `.listen`,
//     `.fetchHistory`, `.close`) come out as genuine Objective-C instance
//     methods, which Swift *does* auto-bridge: the trailing `NSError**`
//     is dropped and the method becomes `throws` — call these as plain
//     `try inner.foo(...)`, no `error:` argument.
//
// Still genuinely unverified (untouched since these wouldn't surface as
// compiler errors, only as wrong-behavior-at-runtime): the exact method
// names/signature gomobile generated for the `MobileMessageListenerProtocol`
// conformance below (`onMessage(_:fromX25519Hex:plaintext:txHash:blockHeight:)`),
// and `HistoryResult`/`ParsedContact` field names (`eventsJSON`, `nextHeight`,
// `address`, `x25519PubHex`) — double-check these against Xcode's
// autocomplete on the real framework if history sync or the listener
// callback silently does nothing. Same caveat now also applies to
// `MobileLogListenerProtocol`/`onLog(_:)` and `MobileSession.setLogListener(_:)`
// (added later, wiring up `mobile.LogListener` — see `LiveLogListener`
// below) — if gateway diagnostic lines never show up in `Log.session`
// despite a real connection/failover happening, check these names first.
//
// None of this affects MockCore or anything built against the
// OpenChatCore protocol — only this file needs edits once the real
// framework exists.
#if canImport(OpenChatMobile)
import OpenChatMobile

// gomobile/gobind prefixes every exported symbol from Go package `mobile`
// with "Mobile" (matching the free functions below — MobileGenerateMnemonic,
// MobileCreateWallet, etc.) — so the bound `mobile.Wallet`/`mobile.Session`
// struct types are already named `MobileWallet`/`MobileSession`, not
// `Wallet`/`Session`. (First guess here was a bare-name typealias; this
// is the correction, confirmed against gomobile's naming convention.)

enum LiveCore: OpenChatCore {
    static func generateMnemonic() throws -> String {
        var error: NSError?
        let result = MobileGenerateMnemonic(&error)
        if let error { throw OpenChatError(message: error.localizedDescription) }
        return result
    }

    static func createWallet() throws -> WalletHandle {
        var error: NSError?
        guard let w = MobileCreateWallet(&error) else {
            throw OpenChatError(message: error?.localizedDescription ?? "createWallet failed")
        }
        return LiveWallet(inner: w)
    }

    static func importWallet(mnemonic: String) throws -> WalletHandle {
        var error: NSError?
        guard let w = MobileImportWallet(mnemonic, &error) else {
            throw OpenChatError(message: error?.localizedDescription ?? "importWallet failed")
        }
        return LiveWallet(inner: w)
    }

    static func parseContactCode(_ code: String) throws -> (address: String, x25519Hex: String) {
        var error: NSError?
        guard let parsed = MobileParseContactCode(code, &error) else {
            throw OpenChatError(message: error?.localizedDescription ?? "invalid contact code")
        }
        return (address: parsed.address, x25519Hex: parsed.x25519PubHex)
    }

    static func makeSession(wallet: WalletHandle, bootstrapCSV: String, caPEM: Data?, insecureSkipVerify: Bool) throws -> NetworkSession {
        guard let liveWallet = wallet as? LiveWallet else {
            throw OpenChatError(message: "LiveCore.makeSession requires a wallet created by LiveCore")
        }
        var error: NSError?
        guard let s = MobileNewSession(liveWallet.inner, bootstrapCSV, caPEM, insecureSkipVerify, &error) else {
            throw OpenChatError(message: error?.localizedDescription ?? "session setup failed")
        }
        return LiveSession(inner: s)
    }
}

private struct LiveWallet: WalletHandle {
    let inner: MobileWallet
    var address: String { inner.address() }
    var encryptionPublicHex: String { inner.encryptionPublicHex() }
    var mnemonic: String { inner.mnemonic() }
    var contactCode: String { inner.contactCode() }
}

/// Bridges `mobile.MessageListener` (app/golang/mobile/session.go) to a
/// plain Swift closure — see the file-level caveat above about verifying
/// this against the real generated protocol.
private final class LiveMessageListener: NSObject, MobileMessageListenerProtocol {
    let handler: (IncomingMessagePayload) -> Bool
    init(_ handler: @escaping (IncomingMessagePayload) -> Bool) { self.handler = handler }

    func onMessage(_ fromAddress: String?, fromX25519Hex: String?, plaintext: Data?, txHash: String?, blockHeight: Int64) -> Bool {
        handler(IncomingMessagePayload(
            fromAddress: fromAddress ?? "",
            fromX25519Hex: fromX25519Hex ?? "",
            plaintext: plaintext ?? Data(),
            txHash: txHash ?? "",
            blockHeight: blockHeight
        ))
    }
}

/// Bridges `mobile.LogListener` (app/golang/mobile/session.go) — the
/// human-readable gateway connect/failover/reconnect diagnostics
/// `pkg/client`'s `Discovery`/`Client.OnEvent` already formats — into
/// `Log.session`. This is specifically what explains a bare
/// "failover exhausted candidates: context deadline exceeded" error:
/// which candidate addresses were actually dialed, in what order, and
/// why each one failed (DNS failure vs. connection refused vs. TLS
/// handshake vs. timeout) — none of which reaches the Swift side
/// otherwise, since `Failover`/`Client` only ever hand back the final
/// aggregated error once every candidate and retry has already been
/// exhausted. Naming follows the same not-yet-independently-verified
/// pattern as `LiveMessageListener` above (see this file's header
/// caveat) — double-check against Xcode's autocomplete on the real
/// framework if these lines never show up.
private final class LiveLogListener: NSObject, MobileLogListenerProtocol {
    func onLog(_ message: String?) {
        Log.session.info("[go] \(message ?? "", privacy: .public)")
    }
}

private final class LiveSession: NetworkSession {
    let inner: MobileSession
    // Held as a property (not a local temporary) so it outlives the
    // call to `setLogListener` — gomobile's generated Swift wrapper
    // for a Go-side callback interface reference doesn't keep its own
    // strong reference to the Swift object implementing it.
    private let logListener = LiveLogListener()

    init(inner: MobileSession) {
        self.inner = inner
        inner.setLogListener(logListener)
    }

    // Note on `error:` (or its absence): gomobile/gobind only gets Swift's
    // automatic NSError**-to-`throws` bridging for genuine Objective-C
    // *instance methods* — which is what every bound `Session`/`Wallet`
    // method below is. The free functions in the enum above (`MobileGenerateMnemonic`
    // etc.) are plain C-style functions, not methods, so those don't get
    // the automatic bridge and keep the explicit `&error` out-parameter.
    // (First pass here wrongly assumed every call needed `error: &error`.)

    func connect(timeoutSeconds: Int64) async throws {
        try await Task.detached(priority: .userInitiated) { [inner] in
            try inner.connect(timeoutSeconds)
        }.value
    }

    var currentGateway: String { inner.currentGateway() }

    // Unlike connect/listen/fetchHistory (which did auto-bridge to
    // `throws`), sendText's `(String, error)` Go return apparently didn't
    // get the same treatment from gobind — confirmed by the compiler
    // still expecting an explicit `error:` argument here. Kept explicit
    // rather than guessing further.
    func sendText(toAddress: String, toX25519Hex: String, text: String) async throws -> String {
        try await Task.detached(priority: .userInitiated) { [inner] in
            var error: NSError?
            let hash = inner.sendText(toAddress, toX25519Hex: toX25519Hex, text: text, error: &error)
            if let error { throw OpenChatError(message: error.localizedDescription) }
            return hash
        }.value
    }

    func listen(onMessage: @escaping (IncomingMessagePayload) -> Bool) async throws {
        let listener = LiveMessageListener(onMessage)
        try await Task.detached(priority: .background) { [inner] in
            try inner.listen(listener)
        }.value
    }

    func stop() { inner.stop() }

    func fetchHistory(fromHeight: Int64, knownX25519Hex: [String: String]) async throws -> (events: [HistoryEventPayload], nextHeight: Int64) {
        try await Task.detached(priority: .userInitiated) { [inner] in
            let knownJSON = String(data: try JSONEncoder().encode(knownX25519Hex), encoding: .utf8) ?? "{}"
            let result = try inner.fetchHistory(fromHeight, knownKeysJSON: knownJSON)
            struct DTO: Decodable {
                let height: Int64, txHash: String, timestampMs: Int64
                let incoming: Bool, peerAddress: String, peerX25519Hex: String, text: String
            }
            let decoded = (try? JSONDecoder().decode([DTO].self, from: Data(result.eventsJSON.utf8))) ?? []
            let events = decoded.map {
                HistoryEventPayload(height: $0.height, txHash: $0.txHash, timestampMs: $0.timestampMs,
                                     incoming: $0.incoming, peerAddress: $0.peerAddress,
                                     peerX25519Hex: $0.peerX25519Hex, text: $0.text)
            }
            return (events: events, nextHeight: result.nextHeight)
        }.value
    }

    func close() {
        inner.stop()
        try? inner.close()
    }
}
#endif
