services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: messagedb
      POSTGRES_USER: messageuser
      POSTGRES_PASSWORD: messagepass
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_messagedb_data:/var/lib/postgresql/data

volumes:
  postgres_messagedb_data:

networks:
  web:
    external: true