version: '3.8'
services:
  account-service:
    image: hvckfy/openchat-accountservice:latest
    environment:
      DBHost: 9.9.9.17
      DBPort: 5432
      DBUser: accountuser
      DBPass: accountpass
      DBName: accountdb
      MTLSPort: 48080
      MTLSCaCrt: /home/certs/ca.crt
      MTLSServiceSrt: /home/certs/account-service.crt
      MTLSServiceKey: /home/certs/account-service.key
    restart: unless-stopped
    volumes:
      - /home/certs/ca.crt:/home/certs/ca.crt:ro
      - /home/certs/account-service.crt:/home/certs/account-service.crt:ro
      - /home/certs/account-service.key:/home/certs/account-service.key:ro
      - /home/heckfy/logs/account-service/:/root/logs/
    networks:
      - web

networks:
  web:
    external: true